version: "3.7"

networks:
    caddy_network:
        driver: bridge

volumes:
    caddy_data:
    caddy_config:

services:
    fastapi:
        container_name: fastapi
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8000:8000

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 5m
            timeout: 5s
            retries: 3
            start_period: 15s
        networks:
            - caddy_network

    caddy:
        container_name: caddy
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile.caddy
        ports:
            - 80:80
            - 443:443
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - fastapi
        environment:
            # Domain and TLS settings
            CADDY_EMAIL: admin@localhost
            CADDY_DOMAIN: fastapi.localhost

            # Proxy settings to communicate with FastAPI service
            CADDY_PROXY_BACKEND: fastapi
            CADDY_PROXY_PORT: 8000
        networks:
            - caddy_network
