# Use Caddy 2.7.4 Alpine as the base image
FROM caddy/caddy:2.7.4-alpine

# Create a directory for the app
RUN mkdir /app

# Copy the Caddyfile into the container
COPY Caddyfile /etc/caddy/Caddyfile

# Set the default DOMAIN environment variable
ENV DOMAIN=localhost

# Use the exec form of CMD to run Caddy with the provided Caddyfile
CMD ["sh", "-c", "if [ -z \"$DOMAIN\" ]; then export DOMAIN=\"localhost\"; fi; caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"]
